### ISSUE TITLE
Truncate() abstraction is missing from the Filesystem interface

### ISSUE THREAD

**Issue by wuman** [blang/vfs#10]
The current Filesystem interface is missing the Truncate() abstraction.

**Comment by blang** [comment]
You're right, it might be useful to include but it also bloats the interfaces.
Currently you can use `OpenFile(name, os.O_TRUNC, 0)` to truncate a file.

**Comment by wuman** [comment]
What we need is the ability to truncate the file to a certain size, which is not provided by the `OpenFile` function.

I do see your concern about bloating the interface though.  We will resort to forking the project if it is understandably not added to the interface.

**Comment by blang** [comment]
You're absolutely right, that can't be covered with a workaround.
What do you think suits better: `fs.Truncate(name,size)` or `file.Truncate(size)`.
I think it might be better to add this to the `File` interface, since  that does not bloat Wrapper Filesystems but you have to open the file first to truncate it.

I honestly don't know many use cases for truncate anyway, so what do you think?

**Comment by wuman** [comment]
For our particular use case where we are implementing an atomic file queue, we only need the `file.Truncate(size)` API.  I think it makes more sense to add this because it doesn't bloat the Filesystem interface.

**Comment by blang** [comment]
Yep i guess that's the best option. Are you already implementing this feature?
