### ISSUE TITLE
Why takes memfs.NewBuffer a pointer to a []byte?

### ISSUE THREAD

**Issue by dwlnetnl** [blang/vfs#8]
IMHO normally it's unnecessary to use a slice pointer because a slice is a pointer type. I'd like hear your reasoning.

**Comment by blang** [comment]
I created an example, have a look at: https://play.golang.org/p/DfsZf5E7cc
Basically by calling `A(buf []int)`, A gets a copy (because copy by value) of the slice datastructure:
Which looks like this internally `{ len int, cap int, array pointer }`. 

But if that slice needs to expand (append if len==cap), the slice datastructure (len, cap, array pointer) need to change:
len+1, cap=2*cap+1, pointer to bigger newly allocated array
But A could only change those in the copy it got. The outside world will never see this change. 
Therefore a reference to the slice is used

**Comment by dwlnetnl** [comment]
Sure thing. I didn't consider the expansion of the passed buffer.
Thanks!
